name: 'Slugify'
description: 'Slugify the commit ref'
inputs:
  sha_length:
    description: 'The length to shorten the commit SHA to'
    required: false
    default: '7'
outputs:
  branch:
    description: 'The slugified branch'
  sha:
    description: 'The <sha_length> character SHA of the commit'
runs:
  using: 'node18'
  main: 'dist/index.js'
